// Voice samples related actions
export const FETCH_VOICES_REQUEST = 'FETCH_VOICES_REQUEST';
export const FETCH_VOICES_SUCCESS = 'FETCH_VOICES_SUCCESS';
export const FETCH_VOICES_FAILURE = 'FETCH_VOICES_FAILURE';

// TTS related actions
export const TTS_SYNTHESIZE_REQUEST = 'TTS_SYNTHESIZE_REQUEST';
export const TTS_SYNTHESIZE_SUCCESS = 'TTS_SYNTHESIZE_SUCCESS';
export const TTS_SYNTHESIZE_FAILURE = 'TTS_SYNTHESIZE_FAILURE';
export const TTS_STATUS_UPDATE = 'TTS_STATUS_UPDATE';
export const TTS_CLEAR_RESULT = 'TTS_CLEAR_RESULT';